auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    endpoint: {{ .Values.loki.s3.endpoint }}
    insecure: {{ .Values.loki.s3.insecure }}
    s3forcepathstyle: {{ .Values.loki.s3.s3forcepathstyle }}
    region: {{ .Values.loki.s3.region }}
    bucketnames: ${OBSERVABILITY_BUCKET_NAME}
    access_key_id: ${STORAGE_ACCESS_KEY_ID}
    secret_access_key: ${STORAGE_SECRET_ACCESS_KEY}

limits_config:
  volume_enabled: true
