receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  transform/promote_resource_attrs:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["deployment_environment"], resource.attributes["deployment.environment"])

exporters:
  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [transform/promote_resource_attrs]
      exporters: [otlphttp/prometheus, debug]
    logs:
      receivers: [otlp]
      exporters: [loki]
    traces:
      receivers: [otlp]
      exporters: [otlphttp/tempo]
