{{- if eq .Values.env.ENV "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-sandbox-secrets
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Values.secrets.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.secrets.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  STORAGE_BUCKET_NAME: {{ .Values.secrets.storageBucketName | quote }}
  STORAGE_ACCESS_KEY_ID: {{ .Values.secrets.storageAccessKeyId | quote }}
  STORAGE_SECRET_ACCESS_KEY: {{ .Values.secrets.storageSecretAccessKey | quote }}
  OBSERVABILITY_BUCKET_NAME: {{ .Values.secrets.observabilityBucketName | quote }}
{{- end }}
