apiVersion: 1

datasources:
  - name: Metrics
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "1m"

  - name: Logs
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"([a-f0-9]+)"'
          url: "$${__value.raw}"
          datasourceUid: tempo

  - name: Traces
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      lokiSearch:
        datasourceUid: loki
      nodeGraph:
        enabled: true

  - name: DB
    type: postgres
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: ${POSTGRES_SSLMODE}
    editable: true
