apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: default
spec:
  replicas: {{ .Values.replicaCount.headlamp }}
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp
      automountServiceAccountToken: true
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:v0.40.1
        args:
        - --in-cluster
        - --plugins-dir=/headlamp/plugins
        ports:
        - containerPort: 4466
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
