{{- if and .Values.ingress .Values.ingress.domain }}
{{- $host := printf "%s.%s" .Values.ingress.subdomains.headlamp .Values.ingress.domain }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-ingress-route
spec:
  entryPoints:
    - {{ if .Values.ingress.tls }}websecure{{ else }}web{{ end }}
  routes:
    - match: Host(`{{ $host }}`) || Host(`www.{{ $host }}`)
      kind: Rule
      services:
        - name: headlamp-service
          port: {{ .Values.headlamp.port }}
{{- if .Values.ingress.tls }}
  tls:
    certResolver: letsencrypt
{{- end }}
{{- end }}
