apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: default
spec:
  replicas: {{ .Values.replicaCount.otelCollector }}
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      annotations:
        checksum/config: {{ .Files.Get "files/otel-collector/otel-collector-config.yaml" | sha256sum }}{{ toYaml (.Values.prometheus | default dict) | sha256sum }}{{ toYaml (.Values.loki | default dict) | sha256sum }}{{ toYaml (.Values.tempo | default dict) | sha256sum }}
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.115.1
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        volumeMounts:
        - name: config
          mountPath: /etc/otelcol-contrib/config.yaml
          subPath: otel-collector-config.yml
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
