server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

storage:
  trace:
    backend: s3
    s3:
      bucket: ${OBSERVABILITY_BUCKET_NAME}
      endpoint: {{ .Values.tempo.s3.endpoint }}
      region: {{ .Values.tempo.s3.region }}
      access_key: ${STORAGE_ACCESS_KEY_ID}
      secret_key: ${STORAGE_SECRET_ACCESS_KEY}
      insecure: {{ .Values.tempo.s3.insecure }}
      forcepathstyle: {{ .Values.tempo.s3.forcepathstyle }}
    wal:
      path: /var/tempo/wal
