apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: default
spec:
  replicas: {{ .Values.replicaCount.loki }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      annotations:
        checksum/config: {{ .Files.Get "files/loki/loki-config.yaml" | sha256sum }}{{ toYaml (.Values.loki | default dict) | sha256sum }}
        checksum/secret: {{ toYaml .Values.secrets | sha256sum }}
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.7.2
        args:
          - -config.file=/etc/loki/loki-config.yaml
          - -config.expand-env=true
        ports:
        - containerPort: 3100
        envFrom:
        - secretRef:
            name: fastapi-sandbox-secrets
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
        - name: loki-storage
          mountPath: /loki
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
      - name: loki-storage
        emptyDir: {}
