apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sandbox-deployment
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: fastapi-sandbox
  template:
    metadata:
      annotations:
        checksum/config: {{ toYaml .Values.env | sha256sum }}
        checksum/secret: {{ toYaml .Values.secrets | sha256sum }}
      labels:
        app: fastapi-sandbox
    spec:
      {{- if .Values.s3.roleArn }}
      serviceAccountName: fastapi-sandbox-sa
      {{- end }}
      containers:
      - name: fastapi-sandbox
        image: {{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}
        imagePullPolicy: {{ .Values.image.api.pullPolicy }}
        envFrom:
        - secretRef:
            name: fastapi-sandbox-secrets
        - configMapRef:
            name: fastapi-sandbox-config-map
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
