{{- if .Values.serviceAccount.roleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-sandbox-sa
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}
{{- end }}
