{{- if ne .Values.env.ENV "local" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fastapi-sandbox-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: fastapi-sandbox-secrets
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: {{ .Values.eso.parameterStorePrefix }}/rds/host
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: {{ .Values.eso.parameterStorePrefix }}/rds/port
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.eso.parameterStorePrefix }}/rds/database_name
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.eso.parameterStorePrefix }}/rds/username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.eso.parameterStorePrefix }}/rds/password
    - secretKey: STORAGE_BUCKET_NAME
      remoteRef:
        key: {{ .Values.eso.parameterStorePrefix }}/s3/bucket_name
{{- end }}
