{{- if ne .Values.env.ENV "local" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
  data:
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: {{ .Values.eso.parameterStorePrefix }}/grafana/username
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.eso.parameterStorePrefix }}/grafana/password
{{- end }}
