apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: default
spec:
  replicas: {{ .Values.replicaCount.tempo }}
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.10.6
        args:
          - -config.file=/etc/tempo/tempo-config.yaml
          - -config.expand-env=true
        ports:
        - containerPort: 3200
        - containerPort: 4317
        - containerPort: 4318
        envFrom:
        - secretRef:
            name: fastapi-sandbox-secrets
        volumeMounts:
        - name: tempo-config
          mountPath: /etc/tempo
        - name: tempo-wal
          mountPath: /var/tempo/wal
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: tempo-config
        configMap:
          name: tempo-config
      - name: tempo-wal
        emptyDir: {}
