replicaCount:
  api: 1

image:
  api:
    repository: fastapi-sandbox
    tag: latest
    pullPolicy: Never

grafana:
  port: 3000

env:
  ENV: local
  POSTGRES_SSLMODE: disable
  STORAGE_PUBLIC_URL: "http://localhost:9000"
  AUTH_ISSUER: "http://mock-oauth2-server:8080/fastapi-sandbox"
  AUTH_AUDIENCE: "default"
  AUTH_JWKS_URI: "http://mock-oauth2-server:8080/fastapi-sandbox/jwks"

externalSecrets:
  enabled: false

traefik:
  enabled: false

ingress:
  enabled: false
  api: ""
  grafana: ""

s3:
  roleArn: ""

loki:
  s3:
    endpoint: "http://minio-service:9000"
    insecure: true
    s3forcepathstyle: true
    region: "us-east-1"

secrets:
  postgresHost: "postgres"
  postgresPort: "5432"
  postgresDb: "db"
  postgresUser: "admin"
  postgresPassword: "qwerty123"
  grafanaAdminUser: "admin"
  storageBucketName: "fastapi-sandbox-local"
  storageAccessKeyId: "admin"
  storageSecretAccessKey: "qwerty123"
  grafanaPassword: "qwerty123"
  minioRootUser: "admin"
  minioRootPassword: "qwerty123"
