replicaCount:
  api: 2

image:
  api:
    repository: jstenghele/juans-fastapi-sandbox
    tag: latest
    pullPolicy: Always

env:
  ENV: production
  POSTGRES_SSLMODE: prefer
  STORAGE_PUBLIC_URL: "https://s3.sa-east-1.amazonaws.com"
  AUTH_ISSUER: "https://dev-76kf5dzezilav06g.us.auth0.com/"
  AUTH_AUDIENCE: "https://juans-fastapi-sandbox"
  AUTH_JWKS_URI: "https://dev-76kf5dzezilav06g.us.auth0.com/.well-known/jwks.json"

traefik:
  enabled: true

ingress:
  enabled: true
  api: juans-fastapi-sandbox.25101999.xyz
  grafana: grafana.juans-fastapi-sandbox.25101999.xyz

s3:
  roleArn: "" # retrieved from parameter store

eso:
  region: "sa-east-1"
  parameterStorePrefix: "/juans-fastapi-sandbox"
