replicaCount:
  grafana: 1
  prometheus: 1
  otelCollector: 1
  loki: 1
  tempo: 1

grafana:
  port: 80

prometheus:
  url: http://prometheus-service:9090

loki:
  url: http://loki-service:3100

tempo:
  url: http://tempo-service:3200
  otlpHttpUrl: http://tempo-service:4318

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector-service:4318
