from enum import Enum


# Env contants
ENV = "ENV"
ENV_LOCAL = "local"
ENV_TESTING = "test"
ENV_PRODUCTION = "production"

# DB constants
POSTGRES_DB = "POSTGRES_DB"
POSTGRES_USER = "POSTGRES_USER"
POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
POSTGRES_HOST = "POSTGRES_HOST"
POSTGRES_PORT = "POSTGRES_PORT"
POSTGRES_SSLMODE = "POSTGRES_SSLMODE"
POSTGRES_HOST_DEFAULT = "postgres"
POSTGRES_PORT_DEFAULT = 5432
POSTGRES_SSLMODE_DEFAULT = "prefer"

# Auth
AUTH_AUDIENCE = "AUTH_AUDIENCE"
AUTH_ISSUER = "AUTH_ISSUER"
AUTH_JWKS_URI = "AUTH_JWKS_URI"

# Logger
LOGGER_NAME = "fastapi-sandbox"

# OpenTelemetry constants
OTEL_SERVICE_NAME = "fastapi-sandbox"
OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"
OTEL_EXPORTER_OTLP_ENDPOINT_DEFAULT = "http://otel-collector:4318"
OTEL_METRIC_EXPORT_INTERVAL_MILLIS = 15000

AUTH_ALGORITHM = "RS256"
AUTH_SCOPE_ADMIN = "admin"

# Cover image
COVER_IMAGE_ALLOWED_CONTENT_TYPES = {"image/jpeg", "image/png", "image/webp"}
COVER_IMAGE_MAX_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB

# Storage
S3_SERVICE_NAME = "s3"
STORAGE_ENDPOINT_URL = "STORAGE_ENDPOINT_URL"
STORAGE_PUBLIC_URL = "STORAGE_PUBLIC_URL"
STORAGE_ACCESS_KEY_ID = "STORAGE_ACCESS_KEY_ID"
STORAGE_SECRET_ACCESS_KEY = "STORAGE_SECRET_ACCESS_KEY"
STORAGE_BUCKET_NAME = "STORAGE_BUCKET_NAME"
STORAGE_REGION = "STORAGE_REGION"
STORAGE_REGION_DEFAULT = "us-east-1"

class Tags(Enum):
  HEALTH_CHECK = "Health check"
  AUTHORS = "Authors"
  BOOKS = "Books"
