receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  transform/promote_resource_attrs:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["deployment_environment"], resource.attributes["deployment.environment"])

exporters:
  otlphttp/prometheus:
    endpoint: {{ .Values.prometheus.url }}/api/v1/otlp
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: {{ .Values.loki.url }}/otlp
    tls:
      insecure: true

  otlphttp/tempo:
    endpoint: {{ .Values.tempo.otlpHttpUrl }}
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [transform/promote_resource_attrs]
      exporters: [otlphttp/prometheus, debug]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp]
      exporters: [otlphttp/tempo]
